tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-secondary-fixed": "#3a1b88",
                "inverse-surface": "#0c0f10",
                "on-secondary": "#f7f0ff",
                "background": "#f5f6f7",
                "on-tertiary-fixed-variant": "#6d104e",
                "surface-tint": "#4a40e0",
                "primary-dim": "#3d30d4",
                "on-surface": "#2c2f30",
                "on-primary": "#f4f1ff",
                "outline-variant": "#abadae",
                "on-error": "#ffefef",
                "inverse-primary": "#8582ff",
                "surface-container-highest": "#dadddf",
                "on-secondary-fixed-variant": "#573da6",
                "tertiary-fixed-dim": "#ee7ebc",
                "secondary": "#6249b2",
                "on-tertiary-container": "#610244",
                "on-background": "#2c2f30",
                "on-primary-fixed-variant": "#1a0099",
                "surface-bright": "#f5f6f7",
                "tertiary-container": "#fd8bca",
                "error-container": "#f74b6d",
                "surface-variant": "#dadddf",
                "error-dim": "#a70138",
                "primary-fixed-dim": "#8885ff",
                "on-tertiary-fixed": "#360024",
                "inverse-on-surface": "#9b9d9e",
                "secondary-container": "#d8caff",
                "primary-fixed": "#9795ff",
                "secondary-fixed": "#d8caff",
                "on-surface-variant": "#595c5d",
                "surface": "#f5f6f7",
                "on-error-container": "#510017",
                "tertiary-dim": "#892a65",
                "surface-container-high": "#e0e3e4",
                "surface-dim": "#d1d5d7",
                "on-primary-container": "#14007e",
                "on-tertiary": "#ffeff4",
                "secondary-fixed-dim": "#cbbaff",
                "error": "#b41340",
                "surface-container-low": "#eff1f2",
                "surface-container": "#e6e8ea",
                "primary": "#4a40e0",
                "outline": "#757778",
                "tertiary-fixed": "#fd8bca",
                "surface-container-lowest": "#ffffff",
                "secondary-dim": "#563ca5",
                "primary-container": "#9795ff",
                "on-secondary-container": "#4e339c",
                "on-primary-fixed": "#000000",
                "tertiary": "#983772"
            },
            fontFamily: {
                "headline": ["Be Vietnam Pro", "Heebo", "sans-serif"],
                "body": ["Assistant", "Inter", "sans-serif"],
                "label": ["Assistant", "Inter", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
        },
    },
}