tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-error-container": "#ffa8a3",
                "surface-bright": "#262c36",
                "error-container": "#9f0519",
                "surface-tint": "#8ff5ff",
                "surface-container-highest": "#20262f",
                "surface-container-low": "#0f141a",
                "on-secondary-fixed-variant": "#005967",
                "outline-variant": "#44484f",
                "surface": "#0a0e14",
                "outline": "#72757d",
                "secondary-dim": "#00cdeb",
                "surface-container-high": "#1b2028",
                "secondary-fixed": "#55e3ff",
                "on-primary-fixed": "#003f43",
                "on-background": "#f1f3fc",
                "tertiary": "#65afff",
                "primary": "#8ff5ff",
                "on-secondary": "#004955",
                "inverse-on-surface": "#51555c",
                "surface-dim": "#0a0e14",
                "background": "#0a0e14",
                "error-dim": "#d7383b",
                "inverse-surface": "#f8f9ff",
                "tertiary-container": "#4aa2f9",
                "on-surface-variant": "#a8abb3",
                "surface-variant": "#20262f",
                "primary-container": "#00eefc",
                "on-secondary-container": "#ebfbff",
                "secondary-fixed-dim": "#00d6f5",
                "on-error": "#490006",
                "on-surface": "#f1f3fc",
                "on-primary-container": "#005359",
                "on-tertiary-fixed-variant": "#003b68",
                "on-tertiary-container": "#00213e",
                "secondary": "#00dcfc",
                "primary-fixed-dim": "#00deec",
                "on-tertiary-fixed": "#001930",
                "on-primary-fixed-variant": "#005e64",
                "on-primary": "#005d63",
                "on-tertiary": "#002e52",
                "error": "#ff716c",
                "secondary-container": "#006878",
                "surface-container-lowest": "#000000",
                "primary-dim": "#00deec",
                "tertiary-dim": "#4aa2f9",
                "tertiary-fixed-dim": "#51a7fe",
                "inverse-primary": "#006a71",
                "primary-fixed": "#00eefc",
                "tertiary-fixed": "#72b5ff",
                "on-secondary-fixed": "#003a44",
                "surface-container": "#151a21"
            },
            fontFamily: {
                "headline": ["Heebo", "Inter", "sans-serif"],
                "body": ["Assistant", "Inter", "sans-serif"],
                "label": ["Assistant", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
        },
    },
}
